SPECIAL_FIELD_FLAG = "__"
def is_flag(text:str):
    return text.startswith(SPECIAL_FIELD_FLAG)
def to_flag(text:str):
    return SPECIAL_FIELD_FLAG+text

MODELS_FIELD = "models"
SEVICES_FIELD = "services"

FLAG_EXTENDS = to_flag("extends")
FLAG_EXCLUDES = to_flag("excludes")
FLAG_INCLUDES = to_flag("includes")

FLAG_FROM = to_flag("from")


TAB = ["\t", " "*4,"*"][1]

# GLOBAL VARS
ATTRIBUTE_NAME_DEFAULT = "name"
ATTRIBUTE_CODE_DEFAULT = "code"

# FRAGMENT VARS
ATTRIBUTE_FRAGMENT_TYPE = "type"
ATTRIBUTE_TYPE = "type"
ATTRIBUTE_DEFAULT = "default"

ATTRIBUTE_FUNCTION_NAME = ATTRIBUTE_NAME_DEFAULT
ATTRIBUTE_FUNCTION_ARGS = "args"
ATTRIBUTE_FUNCTION_KWARGS = "kwargs"
ATTRIBUTE_FUNCTION_OUTPUTS = "outputs"
ATTRIBUTE_FUNCTION_CODE = ATTRIBUTE_CODE_DEFAULT

ATTRIBUTE_FUNCTION_RETURN_ARGS = "args"

ATTRIBUTE_FUNCTION_CALL_NAME = "function"

ATTRIBUTE_VARIABLE_NAME = "name"
ATTRIBUTE_VARIABLE_TYPE = "variable_type"
ATTRIBUTE_VARIABLE_EXPRESSION = "expression"
ATTRIBUTE_VARIABLE_ASSIGN_OPERATOR = "assign_operator"

ATTRIBUTE_FOR_ITERATORS = "iterators"
ATTRIBUTE_FOR_SEQUENCE = "sequence"
ATTRIBUTE_FOR_CODE = ATTRIBUTE_CODE_DEFAULT
ATTRIBUTE_FOR_ELSE_CODE = "else"

ATTRIBUTE_CONDITIONAL_CONDITION = "condition"
ATTRIBUTE_CONDITIONAL_CODE = ATTRIBUTE_CODE_DEFAULT

ATTRIBUTE_CLASS_NAME = ATTRIBUTE_NAME_DEFAULT
ATTRIBUTE_CLASS_ATTRIBUTES = "attributes"
ATTRIBUTE_CLASS_EXTENDS = "extends"
ATTRIBUTE_CLASS_CODE = ATTRIBUTE_CODE_DEFAULT